stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
      - src/data_collection.py
    params:
      - data_collection.test_size
    outs:
      - data/raw
  pre_processing:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw
      - src/data_preprocessing.py
    outs:
      - data/processed
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/processed
      - src/feature_engineering.py
    outs:
      - data/engineered
  model_building:
    cmd: python src/model_building.py
    deps:
      - data/engineered
      - src/model_building.py
    params:
    - model_building.n_estimators
    outs:
      - model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - model.pkl
      - src/model_evaluation.py
    metrics:
      - metrics.json
