stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  pre_processing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/processed
    - src/features/feature_engineering.py
    outs:
    - data/interim
  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/interim
    - src/models/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - models/model.pkl
    - src/models/model_evaluation.py
    metrics:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
