data_collection:
  batch_size: 79210        # max value for dataset is: 79210
  test_size: 0.3           # Split of data (70% training, 30% test)

data_preprocessing:
  upper_quantile: 0.88
  lower_quantile: 0.14
  apply_winsorization: True
  transformation_type: "custom"
  apply_boxcox: False

model_building:
  model_name: "xgboost"   
  kwargs:
    subsample: 0.7777777777777778
    n_estimators: 300
    min_child_weight: 2
    max_depth: 10
    learning_rate: 0.017
    reg_lambda: 0.5555555555555556
    gamma: 0.0
    colsample_bytree: 0.8888888888888888
    reg_alpha: 0.7777777777777777  
